### PR TITLE
fix: skip unexpect deleted model when list model

### LINKED ISSUE #1413: bug: Failed to read file: bad file ... Q4_K_M.yml
### Cortex version

v0.5.0-141

### Issue:
I think I accidentally deleted a model while cleaning my disk with GrandPerspective. Since then, I haven't been able to list out the pulled models.

### Expected: 
The broken model should be disregarded, and other available models are still visible.

Screenshot 2024-10-03 at 19 58 11

### Steps to Reproduce

1. Delete any pulled model
2. Run models list
3. See error

### Screenshots / Logs

Screenshot 2024-10-03 at 19 58 11

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

### PR DESCRIPTION
**Pull request by nguyenhoangthuan99**
## Describe Your Changes

- skip and log when fail to read any model.yml when list model
image

## Fixes Issues

- Closes #1413

### CODE REVIEW

File: engine/commands/model_list_cmd.cc [hunk 1]
```diff
@@ -30,10 +30,19 @@ void ModelListCmd::Exec() {
...
+                fs::path(model_entry.path_to_model_yaml))
+                .string());
+
+      } catch (const std::exception& e) {
+        CTL_WRN("Fail to get model '" + model_entry.model +
+                "' information: " + std::string(e.what()));
+        yaml_handler.Reset();
+        count -= 1;
+        continue;
+      }
```
Comment (namchuai) [inline engine/commands/model_list_cmd.cc:42]: maybe moving `count += 1` to this line is better.

**Review by vansangpfiev — APPROVED** [review]
