### PR TITLE
fix: validate url before pull

### LINKED ISSUE #1270: bug: `cortex pull invalid_url` creates a model folder
### Cortex version

v70

### Describe the Bug

1. `cortex pull https://huggingface.co/cortexso/NONEXISTENT_MODEL`
2. Get "model downloaded successfully"
3. Get "not a valid GGUF file"
4. run `ls /cortexcpp/models` 
5. See that a model folder was created for "nonexistent model name"

```sh
❯ sudo cortex-nightly pull https://huggingface.co/cortexso/mistraaal
Validating download items, please wait..
Start downloading: mistraaal
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17228  100 17228    0     0  58595      0 --:--:-- --:--:-- --:--:-- 58798
Model mistraaal downloaded successfully!
Not a valid GGUF file
❯ ls
mistraaal    
```

### Questions
1. Whats our model download validation sequence?
2. Is this a race condition or just bad sequencing?

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

### PR DESCRIPTION
**Pull request by namchuai**
## Describe Your Changes

- Fix an issue reported from Gabrielle while downloading from hugging face handle and url.

## Fixes Issues

- Closes #1270 

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Review by vansangpfiev — APPROVED** [review]

File: engine/services/model_service.cc [hunk 1]
```diff
@@ -195,13 +194,27 @@ cpp::result<std::string, std::string> ModelService::HandleUrl(
   auto file_name{url_obj.pathParams.back()};
 
   if (author == "cortexso") {
-    // TODO: try to get the branch
     return DownloadModelFromCortexso(model_id);
   }
 
+  if (url_obj.pathParams.size() < 5) {
```
Comment (vansangpfiev) [inline engine/services/model_service.cc:200]: Please add comments

Comment (namchuai) [reply engine/services/model_service.cc:200]: Sorry, I missed this one. I will add comment in the following PR.
