### PR TITLE
Fix/isolate stdout cli server

### LINKED ISSUE #1476: bug: Isolate stdout from the API server and CLI - I sent an API request, but it output an error message to an inactive shell session.
### Cortex version

v1.0.0-168

### Describe the Bug

I have finished the shell session of models list, but somehow, when I send API requests, it keeps stdout from an inactive shell session. See attached screenshot, weird.

### Steps to Reproduce

1. Start API Server
2. Run any command such as models list
3. Send API request
4. See the shell output

### Screenshots / Logs

Screenshot 2024-10-15 at 12 12 48

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [ ] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

### PR DESCRIPTION
**Pull request by nguyenhoangthuan99**
## Describe Your Changes

- Separate stdout for CLI and API server

## Fixes Issues

- Closes #1476

### CODE REVIEW

File: engine/utils/logging_utils.h [hunk 1]
```diff
@@ -22,12 +22,11 @@ inline bool log_verbose = false;
   }
 
 // Use std::cout if not verbose, use trantor log if verbose
-#define CTL_ERR(msg)               \
-  if (log_verbose) {               \
-    LOG_ERROR << msg;              \
-  } else {                         \
-    LOG_ERROR << msg;              \
-    std::cout << msg << std::endl; \
+#define CTL_ERR(msg)  \
```
Comment (vansangpfiev) [inline engine/utils/logging_utils.h]: No need to check for log_verbose

**Review by vansangpfiev — APPROVED** [review]
