### PR TITLE
fix(#1437): allow incasesensitive for branch name

### LINKED ISSUE #1437: bug: Default model was not recommended due to capitalization
### Cortex version
cortex-beta v1.0.0-rc1

### Describe the Bug

When reading from metadata.yml, default branch was not detected due to `34B` vs `34b`
image
image

Existing branches may have inconsistent capitalization - can we make parsing it case-insensitive?
Linked to implementation in #1418

### Steps to Reproduce

_No response_

### Screenshots / Logs

_No response_

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

### PR DESCRIPTION
**Pull request by namchuai**
## Describe Your Changes

- Allow case-insensitive matching for default model variant.

## Screenshot
Screenshot 2024-10-16 at 12 53 13

## Fixes Issues

- Closes #1437 

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Review by nguyenhoangthuan99 — APPROVED** [review]

File: engine/utils/string_utils.h [hunk 1]
```diff
@@ -13,6 +13,11 @@ struct ParsePromptResult {
   std::string ai_prompt;
 };
 
+inline bool EqualsIgnoreCase(const std::string& a, const std::string& b) {
```
Comment (vansangpfiev) [inline engine/utils/string_utils.h:16]: It would be great if we have unit tests for this function

**Review by vansangpfiev — APPROVED** [review]

File: engine/utils/string_utils.h (hunk 1 above)
Comment (namchuai) [reply engine/utils/string_utils.h:16]: yeah, let me add it into another PR, which comes right after this
